### ISSUE TITLE
BrowserAnimationsModule

### ISSUE THREAD

**Issue by alastair-todd** [maxime1992/angular-ngrx-starter#4]
Hi

Could you please explain why `BrowserAnimationsModule `ended up in the core module and not the shared module?

I find it difficult to reason the difference between:

1) "a module you only want to import once"
and
2) "a module to be shared with other feature modules"

I don't yet see why these are mutually exclusive.

Thanks

**Comment by maxime1992** [comment]
Hi @alastair-todd!

Sure, `BrowserAnimationsModuleended` do not need to be shared. **You only have to import it once to get it working for the whole app**. For example into `AppModule`.

But as I do have a dedicated module for things I want to import once (`CoreModule`), this is where I've put it.

I know it can be confusing at the beginning between AppModule, SharedModule, FeatureModule and CoreModule.

Hope I'm clear enough, let me know otherwise

**Comment by maxime1992** [comment]
I'm closing it for now, if you want more information feel free to comment or reopen :)
